module.exports = {
  rouge: "#EE2F2F",
  orange: "#EE602F",
  jauneorange: "#EEA22F",
  jaune: "#E5EE2F",
  jaunevert: "#9AEE2F",
  vert: "#43EE2F",
  turquoise: "#2FEE6C",
  bleuClair: "#2FEED4",
  bleu: "#2FB1EE",
  bleufonce: "#2F4CEE",
  bleuviolet: "#602FEE",
  violet: "#9D2FEE",
  rose: "#EE2FDF",
  gris: "#9c9c9c",
};
